name: Update the staging repository plugin version
on:
  push:
    tags:
      - "v*"

jobs:
  staging_repository_update:
    name: Staging repository update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install packaging tools
        run: |
         sudo apt-get update
         sudo apt-get install -y qttools5-dev-tools

      - name: Install build requirements
        run: pip install -r requirements-dev.txt

      - name: Set version SHA
        run: invoke set-version

      - name: Build zipfile
        run: invoke zipfile-build  --filename LDMP.zip

      - name: Plugin path details
        id: get-zip-details
        run: |
          unzip -o $GITHUB_WORKSPACE/LDMP.zip
          mkdir $GITHUB_WORKSPACE/LDMP.$GITHUB_REF_NAME
          
          cp -r $GITHUB_WORKSPACE/LDMP $GITHUB_WORKSPACE/LDMP.$GITHUB_REF_NAME/

          echo "::set-output name=ZIP_PATH::$GITHUB_WORKSPACE/LDMP.$GITHUB_REF_NAME"
          echo "::set-output name=ZIP_NAME::LDMP.$GITHUB_REF_NAME"

      - name: Uploading plugin build
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-zip-details.outputs.ZIP_NAME }}
          path: ${{ steps.get-zip-details.outputs.ZIP_PATH }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Update custom plugin repository to include latest plugin version
        env:
          PR_NUMBER: ${{ github.event.number }}
          ARTIFACT_URL: ${{ steps.artifact-upload-step.outputs.artifact-url }}
        run: |
          invoke generate-plugin-repo-xml  --prerelease --prerelease-url "$ARTIFACT_URL" --prerelease-time "$(date +'%Y-%m-%dT%H:%M:%SZ')" --prerelease-filename "LDMP_$GITHUB_REF_NAME.zip"
          echo " " >> docs/repository/plugins.xml 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/trends.earth/trends.earth

          git add -A
          git commit -m "Update on the plugins.xml"
          git push origin release

